import { useSession } from "next-auth/react";
import Head from "next/head";
import Redirect from "../components/Redirect";

export default function IndexPage() {
  const { data: session } = useSession();
  if (!session) {
    return (
      <>
        <Head>
          <title>Ceroacien | acelera tu carrera profesional</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <iframe
          loading="lazy"
          className="w-full h-screen"
          src="https://bootcamp-landing-af10b.stackbit.app"
          frameBorder="0"
          allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
          allowFullScreen
        ></iframe>
      </>
    );
  }

  if (session) {
    return <Redirect href="/home" />;
  }
}
