import Head from "next/head";
import Layout from "../components/layout";

export default function IndexPage() {
  return (
    <>
      <Head>
        <title>Ceroacien | acelera tu carrera profesional</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <iframe
        className="w-full h-screen"
        src="https://bootcamp-landing-af10b.stackbit.app"
        frameBorder="0"
        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
        allowFullScreen
      ></iframe>
    </>
  );
}
