import Head from "next/head";
import React from "react";
import Spinner from "../../components/Spinner";

export default function Index() {
  const [isLoading, setIsLoading] = React.useState(true);

  const frameLoaded = () => {
    setIsLoading(false);
  };

  return (
    <>
      <Head>
        <title>Registrate a nuestro programa | ceroacien</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <iframe
          onLoad={frameLoaded}
          className="airtable-embed w-screen h-screen"
          src="https://airtable.com/embed/shrP87WhwwCZW08XT?backgroundColor=blue"
          frameBorder="0"
          style={{ background: "transparent", border: "1px solid #ccc" }}
        ></iframe>
      </main>
    </>
  );
}
